# Generated by Django 4.2.5 on 2023-09-28 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_alter_student_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='portfolio',
        ),
    ]
