# Generated by Django 4.2.5 on 2023-10-17 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0015_projectsinportfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectsInPortfolio',
        ),
    ]
